-- Run this after supabase-setup.sql to load the initial contacts and deals.
-- Safe to run once only — uses INSERT ... ON CONFLICT DO NOTHING.

-- ── Contacts ─────────────────────────────────────────────────────────────────
insert into contacts (id, name, company, email, phone, notes, linked_deal) values
('rvpveyhjk6c44','Gary Mattingley','Isis Windows','gary.mattingley@sky.com','07713261121','','Gary Mattingley'),
('rcrk9a8y2dnof','Sam Halliday','Isis Windows','samhalliday2011@hotmail.com','07525163436','','Sam Halliday'),
('rmvs7m10k27vz','Will Dealey','Isis Windows','info@thetythebarn.co.uk','07802482554','','Will Dealey - Thythe Barn'),
('rqrvsmebwv8wv','Wesley Kernaghan','Isis Windows','oufcwes@yahoo.com','07775591824','','Wesley Kernaghan'),
('rv0e3mjmx1oox','Nick Williams','Isis Windows','ncwhome2@gmail.com','07850990647','','Nick Williams'),
('rxm019sn5mftz','Jaqueline Lewis','Isis Windows','mlew2@sky.com','07860362942','','Jaqueline Lewis'),
('rf6akuvam82c5','Anne Hardwick','Paradise Windows','amhardwick@gmail.com','07771661410','','Anne Hardwick'),
('rfr5dpxc43tzk','Dave Winter','Isis Windows','davebwinter@gmail.com','07491998707','','Dave Winter'),
('rt2sldkwhzwok','Karen Grewal','Paradise Windows','k-grewal@live.com','07516944983','Customer gave no other details','Karen Grewal'),
('rb2tv7251y0rc','Patricia Daley','Isis Windows','daleypatricia@gmail.com','07932159131','','Patricia Daley'),
('rs22jjbp3shxi','Dale Bromell','Isis Windows','dalebromell@icloud.com','07850736485','','Dale Bromell'),
('rcpps8yvmwhsy','Tom Smith','Isis Windows','tom.james.smith87@gmail.com','07841535490','','Tom Smith'),
('r2o9ufw2hbs1k','Chris Liversage','Elite Windows','chris@trinityproperties.co.uk','07974118007','','Chris Liversage'),
('r9ng4b2sh79lx','Helen Williams','Isis Windows','helen.williamscf@outlook.com','','Helen Williams we assume is POA for this property.','Helen Williams'),
('rousx1eh0gocq','Gary','Isis Windows','','07713261121','','Gary'),
('ri6vehiatdhhh','Tim','Isis Windows','tvlandas@gmail.com','','','Tim V'),
('rusxexxwjuxek','Charlotte Roff','Isis Windows','charlotte.roff@pyramidservicesltd.co.uk','','Enquiry came through by phone. Hannah to quote','Charlotte Roff'),
('rokx59jivcvyn','Tim Reynolds','Elite Windows','','07872569222','','Tim Reynolds'),
('rl9k9rdj7gzel','Lyall Kidman','Isis Windows','lyall.kidman@hotmail.co.uk','77022241116','','Lyall Kidman'),
('rtubphn1e8yrk','Andy Ward','Isis Windows','andymic35@gmail.com','07834370771','','Andy Ward'),
('rpr7muuqm417g','Joanne Syson','Elite Windows','bjsyson@gmail.com','07950482586','','Joanne Syson'),
('rj38puh1izydd','Rebecca Wilford','Elite Windows','rebeccarwilford@gmail.com','','','Rebecca Wilford'),
('r0hfofmossggj','Jacquline Campbell','Isis Windows','','07984308001','','Jacquline Campbell'),
('ruyc987l6wbgl','Bob Merchant','Elite Windows','bobmerchant28@outlook.com','07359175213','','Bob Merchant'),
('rwtnm8ibnbpy8','Carrie Southhall','Paradise Windows','carriesouthall@icloud.com','07779025659','','Carrie Southall'),
('r4qutikt2nd5s','Grainne Darnton','Isis Windows','grainne.darnton@gmail.com','','','Grainne Darnton'),
('r7nj560oeo47b','Julie Kennedy','Elite Windows','kennedy.julie19@gmail.com','01993812258','','Julie Kennedy'),
('ri59xtv5bguep','Shane Weir','Elite Windows','shaneweir106@btinternet.com','07795052483','','Shane Weir'),
('ry6ghb4rnp0ka','Lucy Rudd','Elite Windows','lucyrudd@btinternet.com','07912567184','','Lucy Rudd'),
('rxb00vl58rgh1','Emma Dodds','Elite Windows','doddse@ymail.com','','','Emma Dodds'),
('rs1m2ldceudvp','Michel Filippi','Elite Windows','mich31.filippi@gmail.com','07403199247','','Michel Filippi'),
('rxbv8klcbf7hp','Stephanie Bau','Elite Windows','','07722023002','','Stephanie Bau'),
('r1yfv55lt7py2','Helena Coker','Isis Windows','','07931924975','','Helena Coker'),
('rftkbn0t5cgrh','Alex Bekele','Elite Windows','amber-rose-middleton@hotmail.com','07821590044','','Alex Bekele'),
('rxzq5ulv76txh','David Scott','Isis Windows','dvcscott@gmail.com','07976268639','','David Scot'),
('roco2iun240rp','Mrs Starling','Isis Windows','','01235525418','','Mrs. Starling'),
('rtqmrakx0bej5','Tony Steele','Isis Windows','steelebyname@btinternet.com','07818278623','','Tony Steele'),
('ribnqgcs7nva1','Georgina Hicks','Paradise Windows','georginahicks64@icloud.com','','','Georgina Hicks'),
('rn42ik2ry4iis','Jane Rawson-Jones','Isis Windows','janerawson@gmail.com','07751835301','','Jane Rawson-Jones, Jane Rawson'),
('r54evamaujdi3','David Rogerson','Isis Windows','drogerson68@gmail.com','07794620078','','David Rogerson'),
('ry9j966ai97q4','Amber Hatch','Isis Windows','amberkhatch@gmail.com','07979415971','','Amber Hatch'),
('r38vi3gg1oza1','Alison Durrand','Isis Windows','asdurrands@btopenworld.com','07775677089','','Alison Durrand'),
('ro26umgf9rzfa','Cyril Chilson','Paradise Windows','cyril.chilson@protonmail.com','','','Cyril Chilson'),
('ru4kz422hp49y','Marika Dimech','Paradise Windows','williamandmarika.dimech@gmail.com','','','Marika Dimech'),
('ro8ocarhn6vcz','Paul Maskens','Paradise Windows','paul.maskens@transvault.com','07803008554','','Paul Maskens'),
('r9i6jv29lsn5b','Hanne Starling','Isis Windows','hanne.starling@gmail.com','01235525418','','Hanne Starling')
on conflict (id) do nothing;

-- ── Deals ─────────────────────────────────────────────────────────────────────
insert into deals (id, deal_group, deal, company, stage, value, contact, contact_id, location, quote_sent, deposit, comments, quote_visit, survey_date, install_start, install_end, materials_cost, surveyor, install_cost) values
('rjnrhzi0nks52','active','Sam Halliday','Isis Windows','Quote',3907.67,'Sam Halliday','rcrk9a8y2dnof','','2026-04-04',false,'Photo Quote only.  Customer email to say he will contact us if he wishes to pursue with the work.',null,null,null,null,0,'',0),
('r3471ll5wea0i','active','Wesley Kernaghan','Isis Windows','Installation Booked',1023.36,'Wesley Kernaghan','rqrvsmebwv8wv','22 Purslane Dr, Bicester, UK','2026-04-02',false,'',null,null,null,null,0,'',0),
('rrpc5ckkcrr6t','active','Nick Williams','Isis Windows','To Order',1712.89,'Nick Williams','rv0e3mjmx1oox','72 Pensclose, Witney, UK','2026-04-06',false,'',null,null,null,null,0,'',0),
('rikwswan3ci6s','active','Jaqueline Lewis','Isis Windows','Quote',5895.31,'Jaqueline Lewis','rxm019sn5mftz','8 Bunyan Rd, Bicester, UK','2026-04-06',false,'',null,null,null,null,0,'',0),
('r6rgt93f13s51','active','Anne Hardwick','Paradise Windows','Quote',13736.59,'Anne Hardwick','rf6akuvam82c5','Gardiners View, High Street, Goring, Reading RG8 9BB, UK','2026-04-15',false,'',null,null,null,null,0,'',0),
('rt03jllqx4r6l','active','Dave Winter','Isis Windows','Follow Up',0,'Dave Winter','rfr5dpxc43tzk','',null,false,'PDF of Rose Collection sent via email',null,null,null,null,0,null,0),
('r2wqbivmvbsh3','active','Karen Grewal','Paradise Windows','Signed',2153.60,'Karen Grewal','rt2sldkwhzwok','10 Cherry Orchard, Great Coxwell, Faringdon, UK','2026-04-10',false,'H to quote online for a PVC and composite door. Sent PDF of options to client, awaiting outcome.\nEmailed 28/4 requesting address and telephone details to book a survey in.',null,null,null,null,0,'',0),
('rh2hpdtqrgnyx','active','Patricia Daley','Isis Windows','Quote',6641.80,'Patricia Daley','rb2tv7251y0rc','','2026-04-08',false,'Telephone quote for door and a window',null,null,null,null,0,'',0),
('r88q3lh3522s0','active','Dale Bromell','Isis Windows','Quote',13254.67,'Dale Bromell','rs22jjbp3shxi','Farthinghoe Close, Brackley NN13 7AR, UK','2026-04-12',false,'9 windows and one front door',null,null,null,null,0,'',0),
('r10pmt3sb69w2','active','Tom Smith','Isis Windows','Survey',8043.86,'Tom Smith','rcpps8yvmwhsy','26 Bagley Close, Kennington, Oxford, UK','2026-03-30',false,'2 section bay and 9 windows.',null,'2026-04-22',null,null,0,'',0),
('r5qs4hyk2coq7','active','Chris Liversage','Elite Windows','To Order',13025.00,'Chris Liversage','r2o9ufw2hbs1k','Church End, South Leigh, Witney, UK','2026-04-06',false,'10 windows',null,null,null,null,0,'',0),
('renija7ls9ih0','active','Will Dealey - Thythe Barn','Isis Windows','Quote',9853.02,'Will Dealey','rmvs7m10k27vz','Tythe, The Tythe Barn, Launton, Bicester, UK','2026-04-02',false,'Part survey done. Greg to complete.',null,null,null,null,0,'',0),
('rnxdx8hsx0kfq','active','Helen Williams','Isis Windows','Quote',8882.49,'Helen Williams','r9ng4b2sh79lx','29 Jack Straw''s Lane, Headington, Oxford, UK',null,false,'Helen Williams we assume is POA for this property.',null,null,null,null,0,'',0),
('rkwn83fagzr4x','active','Gary','','Awaiting Client',0,'Gary','rousx1eh0gocq','','2026-04-08',false,'Paul C to visit Wednesday 15th April',null,null,null,null,0,'',0),
('r63w63g40dn4s','active','Tim V','Isis Windows','Quote',1783.30,'Tim','ri6vehiatdhhh','','2026-04-12',false,'Photos sent to Paul - Hannah to quote',null,null,null,null,0,'',0),
('rhmxyxd12dxwk','active','Charlotte Roff','Isis Windows','Quote',228.61,'Charlotte Roff','rusxexxwjuxek','','2026-04-12',false,'Enquiry came through by phone',null,null,null,null,0,'',0),
('rgsemn0ulsjym','active','Tim Reynolds','Elite Windows','Quote',5300.00,'Tim Reynolds','rokx59jivcvyn','28 Silverthorne Drive, Reading, UK','2026-04-10',false,'Paul sent quote with no pictures. Three doors, 1 window + shiplap.',null,null,null,null,0,'',0),
('rusltkxdurldh','active','Lyall Kidman','Isis Windows','Survey',2819.96,'Lyall Kidman','rl9k9rdj7gzel','41 Wytham Street, Oxford, UK',null,false,'This is an old job from Paul - Paul C has to do a survey',null,null,null,null,0,'',0),
('r6a8hr7sysm7x','active','Joanne Syson','Elite Windows','Quote',5100.00,'Joanne Syson','rpr7muuqm417g','40 South Street, Middle Barton, Chipping Norton, UK','2026-04-15',false,'',null,null,null,null,0,'',0),
('rrxa11a4k2r2w','active','Rebecca Wilford','Elite Windows','Quote',5129.71,'Rebecca Wilford','rj38puh1izydd','','2026-04-12',false,'She has received a quote but wants to see product.',null,null,null,null,0,'',0),
('rzewe9zqd8ewm','active','Jacquline Campbell','','Service Call',0.00,'Jacquline Campbell','r0hfofmossggj','31 Flemings Road, Woodstock, UK',null,false,'Warranty service call from previous Paul. Door lock problems. Barry to go to site',null,null,null,null,0,'',0),
('ryf6y9hxpnut5','active','Bob Merchant','Elite Windows','Quote',8502.47,'Bob Merchant','ruyc987l6wbgl','Main Road, Long Hanborough, Witney, UK','2026-04-28',false,'Customer wants a showroom visit. Booked quote for 22nd April - 6 windows and 2 doors.',null,null,null,null,0,'',0),
('rj8wwmnyiyzyv','active','Carrie Southall','Paradise Windows','Signed',9507.07,'Carrie Southhall','rwtnm8ibnbpy8','57 Nethercote Road, Tackley, Kidlington, UK','2026-03-25',false,'This is Paul''s job from last month but we have been asked to go and survey.',null,'2026-04-21',null,null,0,'',0),
('r1umlslirdt38','active','Grainne Darnton','Isis Windows','Quote',0,'Grainne Darnton','r4qutikt2nd5s','16 Lamarsh Road, Oxford, UK',null,false,'Six sash windows, a set of french doors and a patio door.',null,null,null,null,0,'',0),
('rlguxirc5hfin','active','Georgina Hicks','Paradise Windows','Quote',0,'',null,'',null,false,'',null,null,null,null,0,null,0),
('rr4i3lv3agaay','active','Jane Rawson-Jones','Isis Windows','Quote',0,'Jane Rawson-Jones','rn42ik2ry4iis','Oatlands Road, Oxford, UK','2026-04-27',false,'',null,null,null,null,0,'',0),
('re0mmjtsbq5ii','active','Julie Kennedy','Elite Windows','Signed',2294.16,'Julie Kennedy','r7nj560oeo47b','19 Mavor Cl, Woodstock, UK','2026-04-15',false,'Set of french doors',null,null,null,null,0,'',0),
('rm9xjoz3b82fy','active','Gary Mattingles','Isis Windows','To Order',1124.03,'',null,'','2026-04-14',false,'',null,null,null,null,0,null,0),
('rtrjq56epkj39','active','Shane Weir','Elite Windows','Quote',16396.47,'Shane Weir','ri59xtv5bguep','Kirtlington, Kidlington OX5 3HE, UK','2026-04-16',false,'',null,null,null,null,6661.27,'',0),
('rtqffgxg9ry8y','active','Gary Mattingley','Isis Windows','Quote',1124.03,'Gary Mattingley','rvpveyhjk6c44','27 Merlin Way, Bicester, UK','2026-04-15',false,'Gary chased up delivery 28/4',null,null,null,null,0,'',0),
('ruqvy818o451t','active','Nick Williams','Isis Windows','Quote',1712.89,'Nick Williams','rv0e3mjmx1oox','51 Farmington Dr, Witney, UK','2026-04-04',false,'',null,null,null,null,0,'',0),
('r5bbe21qgvgtc','active','Lucy Rudd','Elite Windows','Quote',8430.52,'Lucy Rudd','ry6ghb4rnp0ka','Rose Cottage, Weald, Bampton, Oxfordshire, UK',null,false,'6 windows 1 door',null,null,null,null,0,'',0),
('rgryq999pio4x','active','Emma Dodds','Elite Windows','Quote',1033.37,'Emma Dodds','rxb00vl58rgh1','41 Ridgeway Road, Headington, Oxford, UK','2026-04-20',false,'1 window',null,null,null,null,0,'',0),
('rab7p1d9d3bha','active','Michel Filippi','','Quote',0,'Michel Filippi','rs1m2ldceudvp','Bretch Hill, Banbury OX16 0LT, UK',null,false,'Sent email requesting photo of the door',null,null,null,null,0,'',0),
('re0he31e0jgn6','active','Stephanie Bau','Elite Windows','Quote',4900.00,'Stephanie Bau','rxbv8klcbf7hp','','2026-04-20',false,'',null,null,null,null,0,'',0),
('r2xw8guyxw7e8','active','Helena Coker','Isis Windows','To Order',1477.11,'Helena Coker','r1yfv55lt7py2','27 Palmer Road, Headington, Oxford, UK','2026-04-17',false,'This was a job of Paul''s. Paul C just surveyed it.',null,null,null,null,0,'',0),
('rxf9uxhx9fpyb','active','Alex Bekele','Elite Windows','To Order',2280.00,'Alex Bekele','rftkbn0t5cgrh','30 Bicester Road, Kidlington, UK',null,false,'',null,null,null,null,0,'',0),
('ra60ygyjr2wc2','active','David Scot','Isis Windows','Quote',26424.38,'David Scott','rxzq5ulv76txh','231A Woodstock Road, Oxford, UK','2026-04-23',false,'This job was originally quoted last year by Paul J. Paul C has said we will honour the original quotation.',null,null,null,null,0,'',0),
('rmmanjocf6df3','active','Mrs. Starling','Isis Windows','Quote',0,'Mrs Starling','roco2iun240rp','40 Wootton Road, Abingdon, UK',null,false,'Paul to visit site on 25/4',null,null,null,null,0,'',0),
('rcww33nfaivi0','active','Tony Steele','Isis Windows','Quote',0,'Tony Steele','rtqmrakx0bej5','2 Upper Campsfield Road, Kidlington OX20 1QF, UK',null,false,'Paul to visit site on 6/5',null,null,null,null,0,'',0),
('rbc037963o8fb','active','Georgina Hicks','Paradise Windows','Quote',0,'Georgina Hicks','ribnqgcs7nva1','',null,false,'White UPVC, Frosted glass on the top and solid on the bottom 50/50 if possible and no cat flap',null,null,null,null,0,'',0),
('rs5k4zbo8ejan','active','Jane Rawson','Isis Windows','Quote',0,'Jane Rawson-Jones','rn42ik2ry4iis','Oatlands Road, Oxford, UK','2026-04-27',false,'Front door (and probably also the small window immediately above it).',null,null,null,null,0,'',0),
('r3qztco4970w8','active','David Rogerson','Isis Windows','Quote',0,'David Rogerson','r54evamaujdi3','',null,false,'New window units (as moisture buildup inside the window) keeping existing frames. Hannah to quote',null,null,null,null,0,'',0),
('rj74zxeipccq7','active','Amber Hatch','Isis Windows','Quote',0,'Amber Hatch','ry9j966ai97q4','Edgeway Road, Marston, Oxford OX3 0HF, UK',null,false,'Wants quote for PVC sash.',null,null,null,null,0,'',0),
('rt12z3f021vh9','active','Alison Durrand','Isis Windows','Quote',0,'Alison Durrand','r38vi3gg1oza1','',null,false,'Large french door has condensation inside the length.',null,null,null,null,0,'',0),
('rzdazdnaz1jad','active','Cyril Chilson','Paradise Windows','Quote',0,'Cyril Chilson','ro26umgf9rzfa','33 Harpes Road, Oxford OX2 7QJ, UK',null,false,'Quote required for replacing sitting room box window and the front door.',null,null,null,null,0,'',0),
('rxa2wkgszbm9n','active','Marika Dimech','Paradise Windows','Quote',0,'Marika Dimech','ru4kz422hp49y','',null,false,'This is an old job of Pauls. She wants a requote.',null,null,null,null,0,'',0),
('rv18xkds2gt1a','active','Paul Maskens','Paradise Windows','Quote',288.00,'Paul Maskens','ro8ocarhn6vcz','','2026-04-28',false,'Wants trickle vents added to two existing ground floor windows.',null,null,null,null,0,'',0),
('raw655ex7yg48','active','Chris Liversage','Elite Windows','Quote',16162.78,'Chris Liversage','r2o9ufw2hbs1k','','2026-04-28',false,'',null,null,null,null,0,'',0),
('rwp9y3t2f0coc','active','Hanne Starling','Isis Windows','Quote',7183.20,'Hanne Starling','r9i6jv29lsn5b','40 Wootton Road, Abingdon, UK','2026-04-28',false,'Quote for both windows and doors',null,null,null,null,0,'',0),
('rq1i3cw4ii9dv','won','Andy Ward','Isis Windows','Installation Booked',6088.34,'Andy Ward','rtubphn1e8yrk','17 Great Close Road, Yarnton, Kidlington, UK','2026-04-15',false,'Paul J has already done work here previously and now customer wants further work.','2026-04-15','2026-04-17','2026-04-28','2026-04-30',0,'',0)
on conflict (id) do nothing;
